# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"

#Uncomment the lines below to configure your website in a second language.
[zh]
   languageCode = "zh-Hans"
   contentDir = "content/zh"

   [zh.params]
    description = ""
  [[zh.menu.main]]
  name = "主页"
  url = "#home_slider"
  weight = 1

  [[zh.menu.main]]
  name = "简介"
  url = "#about"
  weight = 2

  [[zh.menu.main]]
  name = "博客"
  url = "#posts"
  weight = 3

  [[zh.menu.main]]
  name = "讲座"
  url = "#talks"
  weight = 4

  [[zh.menu.main]]
  name = "生态"
  url = "#required"
  weight = 5

  [[zh.menu.main]]
  name = "文档"
  url = "docs/"
  weight = 6

  
  # Right Menu

[[zh.menu.main_right]]
  name = "<i class=\"fab fa-github\" style=\"color: #eb1616; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://github.com/volcano-sh/"
  weight = 10

[[zh.menu.main_right]]
  name = "<i class=\"fab fa-twitter\" style=\"color: #eb1616; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://twitter.com/volcano_sh"
  weight = 20

[[zh.menu.main_right]]
  name = "<i class=\"fab fa-slack\" style=\"color: #eb1616; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://volcano-sh.slack.com"
  weight = 30

# Documentation 

[[zh.menu.docs]]
  name = "主页"
  weight = 1
  identifier = "home"

[[zh.menu.docs]]
  name = "开始"
  weight = 2
  identifier = "getting-started"

[[zh.menu.docs]]
  name = "概念"
  weight = 3
  identifier = "concepts"

[[zh.menu.docs]]
  name = "Scheduler"
  weight = 4
  identifier = "scheduler"

[[zh.menu.docs]]
  name = "CLI"
  weight = 5
  identifier = "cli"

[[zh.menu.docs]]
 name = "贡献"
  weight = 6
  identifier = "contribution"

  # Blogs

[[zh.menu.posts]]
  name = "讲解"
  weight = 5
  identifier = "tutorials"

[[zh.menu.posts]]
  name = "顾客"
  weight = 10
  identifier = "customers"

 