# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"

#Uncomment the lines below to configure your website in a second language.
[zh]
   languageCode = "zh-Hans"
   contentDir = "content/zh"

  [[zh.menu.main]]
  name = "主页"
  url = "#home_slider"
  weight = 1

  [[zh.menu.main]]
  name = "简介"
  url = "#about"
  weight = 2

  [[zh.menu.main]]
  name = "博客"
  url = "#posts"
  weight = 4

  [[zh.menu.main]]
  name = "生态"
  url = "#required"
  weight = 3

[zh.params]
  version_menu = "文档"

[[zh.params.versions]]
  name = "latest"
  url = "/zh/docs"

[[zh.params.versions]]
  name = "v1.11.0"
  url = "/zh/docs/v1-11-0"

[[zh.params.versions]]
  name = "v1.10.0"
  url = "/zh/docs/v1-10-0"

[[zh.params.versions]]
  name = "v1.9.0"
  url = "/zh/docs/v1-9-0"

[[zh.params.versions]]
  name = "v1.8.2"
  url = "/zh/docs/v1-8-2"

[[zh.params.versions]]
  name = "v1.7.0"
  url = "/zh/docs/v1-7-0"

# Right Menu

[[zh.menu.main_right]]
  name = "<i class=\"fab fa-github\" style=\"color: #000000; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://github.com/volcano-sh/"
  weight = 10

[[zh.menu.main_right]]
  name = "<i class=\"fab fa-twitter\" style=\"color: #1ea1f3; font-size: 1rem; line-height: 1.25\"></i>"
  url = "https://twitter.com/volcano_sh"
  weight = 20

[[zh.menu.main_right]]
  name = "<img src=\"/img/icon_slack.svg\" alt=\"slack\" style=\" font-size: 1rem; line-height: 1.25; width:20px; height:20px; margin-top: 9px;\">"
  post = ""
  url = "https://cloud-native.slack.com/archives/C011GJDQS0N"
  weight = 30

# Documentation version latest

[[zh.menu.docs]]
  name = "主页"
  weight = 1
  identifier = "home"

[[zh.menu.docs]]
  name = "开始"
  weight = 2
  identifier = "getting-started"

[[zh.menu.docs]]
  name = "概念"
  weight = 3
  identifier = "concepts"

[[zh.menu.docs]]
  name = "关键特性"
  weight = 4
  identifier = "features"

[[zh.menu.docs]]
  name = "生态"
  weight = 5
  identifier = "zoology"

[[zh.menu.docs]]
  name = "Scheduler"
  weight = 6
  identifier = "scheduler"

[[zh.menu.docs]]
  name = "CLI"
  weight = 7
  identifier = "cli"

[[zh.menu.docs]]
  name = "贡献"
  weight = 8
  identifier = "contribution"

# Documentation version v1.11.0

[[zh.menu.v1-11-0]]
  name = "主页"
  weight = 1
  identifier = "home"

[[zh.menu.v1-11-0]]
  name = "开始"
  weight = 2
  identifier = "getting-started"

[[zh.menu.v1-11-0]]
  name = "概念"
  weight = 3
  identifier = "concepts"

[[zh.menu.v1-11-0]]
  name = "关键特性"
  weight = 4
  identifier = "features"

[[zh.menu.v1-11-0]]
  name = "生态"
  weight = 5
  identifier = "zoology"

[[zh.menu.v1-11-0]]
  name = "Scheduler"
  weight = 6
  identifier = "scheduler"

[[zh.menu.v1-11-0]]
  name = "CLI"
  weight = 7
  identifier = "cli"

[[zh.menu.v1-11-0]]
  name = "贡献"
  weight = 8
  identifier = "contribution"

# Documentation version v1.10.0

[[zh.menu.v1-10-0]]
  name = "主页"
  weight = 1
  identifier = "home"

[[zh.menu.v1-10-0]]
  name = "开始"
  weight = 2
  identifier = "getting-started"

[[zh.menu.v1-10-0]]
  name = "概念"
  weight = 3
  identifier = "concepts"

[[zh.menu.v1-10-0]]
  name = "生态"
  weight = 4
  identifier = "zoology"

[[zh.menu.v1-10-0]]
  name = "Scheduler"
  weight = 5
  identifier = "scheduler"

[[zh.menu.v1-10-0]]
  name = "CLI"
  weight = 6
  identifier = "cli"

[[zh.menu.v1-10-0]]
  name = "贡献"
  weight = 7
  identifier = "contribution"


# Documentation version v1.9.0

[[zh.menu.v1-9-0]]
  name = "主页"
  weight = 1
  identifier = "home"

[[zh.menu.v1-9-0]]
  name = "开始"
  weight = 2
  identifier = "getting-started"

[[zh.menu.v1-9-0]]
  name = "概念"
  weight = 3
  identifier = "concepts"

[[zh.menu.v1-9-0]]
  name = "生态"
  weight = 4
  identifier = "zoology"

[[zh.menu.v1-9-0]]
  name = "Scheduler"
  weight = 5
  identifier = "scheduler"

[[zh.menu.v1-9-0]]
  name = "CLI"
  weight = 6
  identifier = "cli"

[[zh.menu.v1-9-0]]
  name = "贡献"
  weight = 7
  identifier = "contribution"

# Documentation version v1.8.2

[[zh.menu.v1-8-2]]
  name = "主页"
  weight = 1
  identifier = "home"

[[zh.menu.v1-8-2]]
  name = "开始"
  weight = 2
  identifier = "getting-started"

[[zh.menu.v1-8-2]]
  name = "概念"
  weight = 3
  identifier = "concepts"

[[zh.menu.v1-8-2]]
  name = "生态"
  weight = 4
  identifier = "zoology"

[[zh.menu.v1-8-2]]
  name = "Scheduler"
  weight = 5
  identifier = "scheduler"

[[zh.menu.v1-8-2]]
  name = "CLI"
  weight = 6
  identifier = "cli"

[[zh.menu.v1-8-2]]
  name = "贡献"
  weight = 7
  identifier = "contribution"

# Documentation version v1.7.0

[[zh.menu.v1-7-0]]
  name = "主页"
  weight = 1
  identifier = "home"

[[zh.menu.v1-7-0]]
  name = "开始"
  weight = 2
  identifier = "getting-started"

[[zh.menu.v1-7-0]]
  name = "概念"
  weight = 3
  identifier = "concepts"

[[zh.menu.v1-7-0]]
  name = "生态"
  weight = 4
  identifier = "zoology"

[[zh.menu.v1-7-0]]
  name = "Scheduler"
  weight = 5
  identifier = "scheduler"

[[zh.menu.v1-7-0]]
  name = "CLI"
  weight = 6
  identifier = "cli"

[[zh.menu.v1-7-0]]
  name = "贡献"
  weight = 7
  identifier = "contribution"

# Blogs

[[zh.menu.posts]]
  name = "讲解"
  weight = 5
  identifier = "tutorials"

[[zh.menu.posts]]
  name = "顾客"
  weight = 10
  identifier = "customers"

