# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#home_slider"
  weight = 1

[[main]]
  name = "About"
  url = "#about"
  weight = 2



[[main]]
  name = "Blog"
  url = "#posts"
  weight = 4


[[main]]
  name = "Why Volcano"
  url = "#required"
  weight = 3

#[[main]]
  #name = "Documentation"
  #url = "docs/"
  #weight = 6


[[main_right]]
  name = "<i class=\"fab fa-github\" style=\"color: #000000; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://github.com/volcano-sh/"
  weight = 10

[[main_right]]
  name = "<i class=\"fab fa-x-twitter\" style=\"color: #000000; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://twitter.com/volcano_sh"
  weight = 20

[[main_right]]
  
  name = "<img src=\"/img/icon_slack.svg\" alt=\"slack\" style=\" font-size: 1rem; line-height: 1.25; width:20px; height:20px; margin-top: 9px;\">"
  post = ""
  url = "https://cloud-native.slack.com/archives/C011GJDQS0N"
  weight = 30

# Documentation version latest

[[docs]]
  name = "Home"
  weight = 1
  identifier = "home"

[[docs]]
  name = "Getting Started"
  weight = 2
  identifier = "getting-started"

[[docs]]
  name = "Concepts"
  weight = 3
  identifier = "concepts"

[[docs]]
  name = "Key Features"
  weight = 4
  identifier = "features"

[[docs]]
  name = "Ecosystem"
  weight = 5
  identifier = "ecosystem"

[[docs]]
  name = "Scheduler"
  weight = 6
  identifier = "scheduler"

[[docs]]
  name = "CLI"
  weight = 7
  identifier = "cli"

[[docs]]
  name = "Contribution"
  weight = 8
  identifier = "contribution"

# Documentation version v1.12.0

[[v1-12-0]]
  name = "Home"
  weight = 1
  identifier = "home"

[[v1-12-0]]
  name = "Getting Started"
  weight = 2
  identifier = "getting-started"

[[v1-12-0]]
  name = "Concepts"
  weight = 3
  identifier = "concepts"

[[v1-12-0]]
  name = "Key Features"
  weight = 4
  identifier = "features"

[[v1-12-0]]
  name = "Ecosystem"
  weight = 5
  identifier = "ecosystem"

[[v1-12-0]]
  name = "Scheduler"
  weight = 6
  identifier = "scheduler"

[[v1-12-0]]
  name = "CLI"
  weight = 7
  identifier = "cli"

[[v1-12-0]]
  name = "Contribution"
  weight = 8
  identifier = "contribution"

# Documentation version v1.11.0

[[v1-11-0]]
  name = "Home"
  weight = 1
  identifier = "home"

[[v1-11-0]]
  name = "Getting Started"
  weight = 2
  identifier = "getting-started"

[[v1-11-0]]
  name = "Concepts"
  weight = 3
  identifier = "concepts"

[[v1-11-0]]
  name = "Key Features"
  weight = 4
  identifier = "features"

[[v1-11-0]]
  name = "Ecosystem"
  weight = 5
  identifier = "ecosystem"

[[v1-11-0]]
  name = "Scheduler"
  weight = 6
  identifier = "scheduler"

[[v1-11-0]]
  name = "CLI"
  weight = 7
  identifier = "cli"

[[v1-11-0]]
  name = "Contribution"
  weight = 8
  identifier = "contribution"


# Documentation version v1.10.0

[[v1-10-0]]
  name = "Home"
  weight = 1
  identifier = "home"

[[v1-10-0]]
  name = "Getting Started"
  weight = 2
  identifier = "getting-started"

[[v1-10-0]]
  name = "Concepts"
  weight = 3
  identifier = "concepts"

[[v1-10-0]]
  name = "Ecosystem"
  weight = 4
  identifier = "ecosystem"

[[v1-10-0]]
  name = "Scheduler"
  weight = 5
  identifier = "scheduler"

[[v1-10-0]]
  name = "CLI"
  weight = 6
  identifier = "cli"

[[v1-10-0]]
  name = "Contribution"
  weight = 7
  identifier = "contribution"


# Documentation version v1.9.0

[[v1-9-0]]
  name = "Home"
  weight = 1
  identifier = "home"

[[v1-9-0]]
  name = "Getting Started"
  weight = 2
  identifier = "getting-started"

[[v1-9-0]]
  name = "Concepts"
  weight = 3
  identifier = "concepts"

[[v1-9-0]]
  name = "Ecosystem"
  weight = 4
  identifier = "ecosystem"

[[v1-9-0]]
  name = "Scheduler"
  weight = 5
  identifier = "scheduler"

[[v1-9-0]]
  name = "CLI"
  weight = 6
  identifier = "cli"

[[v1-9-0]]
  name = "Contribution"
  weight = 7
  identifier = "contribution"

# Documentation version v1.8.2

[[v1-8-2]]
  name = "Home"
  weight = 1
  identifier = "home"

[[v1-8-2]]
  name = "Getting Started"
  weight = 2
  identifier = "getting-started"

[[v1-8-2]]
  name = "Concepts"
  weight = 3
  identifier = "concepts"

[[v1-8-2]]
  name = "Ecosystem"
  weight = 4
  identifier = "ecosystem"

[[v1-8-2]]
  name = "Scheduler"
  weight = 5
  identifier = "scheduler"

[[v1-8-2]]
  name = "CLI"
  weight = 6
  identifier = "cli"

[[v1-8-2]]
  name = "Contribution"
  weight = 7
  identifier = "contribution"

# Documentation version v1.7.0

[[v1-7-0]]
  name = "Home"
  weight = 1
  identifier = "home"

[[v1-7-0]]
  name = "Getting Started"
  weight = 2
  identifier = "getting-started"

[[v1-7-0]]
  name = "Concepts"
  weight = 3
  identifier = "concepts"

[[v1-7-0]]
  name = "Ecosystem"
  weight = 4
  identifier = "ecosystem"

[[v1-7-0]]
  name = "Scheduler"
  weight = 5
  identifier = "scheduler"

[[v1-7-0]]
  name = "CLI"
  weight = 6
  identifier = "cli"

[[v1-7-0]]
  name = "Contribution"
  weight = 7
  identifier = "contribution"

# Blogs

[[posts]]
  name = "Tutorials"
  weight = 5
  identifier = "tutorials"

[[posts]]
  name = "Customers"
  weight = 10
  identifier = "customers"
